### ISSUE TITLE
Installation fails on fedora 35 at complilation with gcc

### ISSUE THREAD

**Issue by Archehandoro** [hyperskill/hs-test-python#20]
Processing dependencies for hs-test-python==6.0.0
Searching for psutil==5.8.0
Reading https://pypi.org/simple/psutil/
Downloading
https://files.pythonhosted.org/packages/e1/b0/7276de53321c12981717490516b7e612364f2cb372ee8901bd4a66a000d7/psutil-5.8.0.tar.gz#sha256=0c9ccb99ab76025f2f0bbecf341d4656e9c1351db8cc8a03ccd62e318ab4b5c6
Best match: psutil 5.8.0
Processing psutil-5.8.0.tar.gz
Writing /tmp/easy_install-vfzzyes_/psutil-5.8.0/setup.cfg
Running psutil-5.8.0/setup.py -q bdist_egg --dist-dir
/tmp/easy_install-vfzzyes_/psutil-5.8.0/egg-dist-tmp-b7j6nyl7
psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or
directory
9 | #include <Python.h>
| ^~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command '/usr/bin/gcc' failed
with exit code 1

**Comment by aaaaaa2493** [comment]
@Archehandoro Hi! Do you have Python 3.10 installed? Currently, `psutil` is not supported in Python 3.10, and since `hs-test-python` is using such dependency, we do not support Python 3.10 as well. In this case, I suggest temporarily using 3.9 or lower at the moment.

https://github.com/giampaolo/psutil/issues/1994

**Comment by Archehandoro** [comment]
@aaaaaa2493 Hi! Actually I do, it must be the default version in fedora 35. However, it won't install on my venv on 3.9 either. Could it be the venv got updated to version 3.10 as well?

**Comment by aaaaaa2493** [comment]
@Archehandoro If you use `pip` to install dependencies, check that you are using the correct version of `pip` that  points to your Python 3.9. 

E.g. in your case:
`pip install ...` installs using Python 2
`pip3 install ...` installs using Python 3.10
`pip3.9 install ...` installs using Python 3.9

If you do not have an appropriate `pip` installed, you need to run the command `dnf install python3.9-pip` or `python3.9 -m pip install pip`.

Also, before installing the dependencies, make sure you have activated your virtual environment.

**Comment by aaaaaa2493** [comment]
@Archehandoro Hi! I've implemented a [fix](https://github.com/hyperskill/hs-test-python/commit/4a5ea0ede8df9f789bb37e3fb28e72ccffb613d9) that works while `psutil` is not able to update to Python 3.10. You can use Python 3.10 to solve projects.
