### ISSUE TITLE
Cannot start Django server (Fedora 35)

### ISSUE THREAD

**Issue by acrtr1984** [hyperskill/hs-test-python#22]
I'm trying to submit Stage 1/5: Main page header from the HyperNews Project.  My code runs correctly and I can see expected output of “Coming soon” at `localhost:8000`

However when I go to check my work in pycharm I'm getting the message

`Cannot start Django server because cannot find "Starting development server at" in process' output`

I also tried pip installing git commit `4a5ea0e` via `pip install git+https://github.com/hyperskill/hs-test-python.git` with the same results

I'm on Fedora 35 which is on Python 3.10

**Comment by acrtr1984** [comment]
I'm having the same Issue on Python 3.9.8

**Comment by aaaaaa2493** [comment]
@acrtr1984  Hi! Can you please share your solution for the project, so I can debug it?

**Comment by aaaaaa2493** [comment]
@acrtr1984 Hi! I reviewed your support ticket and [fixed](https://github.com/hyperskill/hs-test-python/commit/4cd8323a1e6f75c69c7b78e62214289a4b15acac) the testing library.
To update the testing library in your project, please do the following:

1. Open `Terminal` tab in PyCharm
2. Run `pip3 uninstall hs-test-python`
3. Run `pip3 install -r requirements.txt`

After executing these commands, you will have the fixed library on your computer.

If it doesn't help, please reopen this issue.

**Comment by sergey-shirnin** [comment]
@aaaaaa2493 so which link to use to install correct hs-test-python?
I have the issue with requirents like this
https://github.com/hyperskill/hs-test-python/archive/release.tar.gz

**Comment by aaaaaa2493** [comment]
@sergey-shirnin Yes, that's the correct link. If you still have issues please, submit support request - https://support.hyperskill.org/hc/en-us/requests/new
