### ISSUE TITLE
filename attribute of SyntaxError exceiption is None

### ISSUE THREAD

**Issue by inuur** [hyperskill/hs-test-python#26]
The library works with `filename` attribute that is `None` in that case https://vyahhi.myjetbrains.com/youtrack/issue/ALTCBUG-10280. It leads to `UnexepctedError` instead of `UserException`.

**Comment by aaaaaa2493** [comment]
@inuur Outcome here is `Error during testing`, not `Unexpected error` and therefore it's not a bug. Without reproducible code example, nothing to fix here.
