### ISSUE TITLE
hs-test-python not available as installable conda or pip package

### ISSUE THREAD

**Issue by nhstanley** [hyperskill/hs-test-python#31]
Hi, I'm trying to do the `Read Quality Control` bioinformatics project on Hyperskill. However, in PyCharm, it insists I need to install `hs-test-python`.  When I try to automatically install it by clicking "Install requirement", it fails. When I try to install it via the command line, it fails. Here is the error:

```
conda install -p ~/miniconda3/envs/hyperskill hs-test-python -y
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - hs-test-python

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

So this package is not available in `conda-forge` or the regular anaconda pkgs channels. Since it is required to do this in PyCharm and impossible to do on the website, it would be good to have an official release that is easy to install via conda or pip. I will clone the repo and install manually, but others might not be able to.

**Comment by aaaaaa2493** [comment]
@nhstanley Hi! Looks like anaconda cannot download packages located on GitHub. You can try to install the library using an absolute path to this repo `pip install https://github.com/hyperskill/hs-test-python/archive/release.tar.gz`. Make sure that it is installed in the virtual environment that is created for this PyCharm project.

Another way is to use regular Python (not conda), it is proved to be working in Python 3.6 to 3.10. You can choose an interpreter when downloading the project from the Hyperksill. This way, this library should be installed automatically.

**Comment by nhstanley-insitro** [comment]
Thanks for the response. I did end up installing it with `pip` but that wasn't the problem. Here's the response I got from Jetbrains Support:

>Please try re-creating the project by following the steps below:
> 1. Go to the affected JetBrains Academy project’s directory and move it somewhere else or make a backup.
> 2. On the Welcome Screen of your IDE, go to the My Courses tab.
> 3. Highlight the affected project and click ✕.
> 4. Select Remove Course.
> 5. Start a JetBrains Academy project by going to the JetBrains Academy tab in File | Learn and Teach | Browse Courses.
>
>Also, our projects don't work with Anaconda Python. You can try to configure a new Python interpreter using this instruction. Then please try installing the required packages. 

That solved my problem. So, it was my mistake for over-complicating setup of the IDE for running the tasks. Thanks for the help and please go ahead and close this issue.

**Comment by nhstanley** [comment]
Thanks for the response. I did end up installing it with `pip` but that wasn't the problem. Here's the response I got from Jetbrains Support:

>Please try re-creating the project by following the steps below:
> 1. Go to the affected JetBrains Academy project’s directory and move it somewhere else or make a backup.
> 2. On the Welcome Screen of your IDE, go to the My Courses tab.
> 3. Highlight the affected project and click ✕.
> 4. Select Remove Course.
> 5. Start a JetBrains Academy project by going to the JetBrains Academy tab in File | Learn and Teach | Browse Courses.
>
>Also, our projects don't work with Anaconda Python. You can try to configure a new Python interpreter using this instruction. Then please try installing the required packages. 

That solved my problem. So, it was my mistake for over-complicating setup of the IDE for running the tasks. Thanks for the help and please go ahead and close this issue.
