### ISSUE TITLE
this can't be located as a package for pycharm

### ISSUE THREAD

**Issue by lNyx** [hyperskill/hs-test-python#8]
when openning a python Hyperskill project in pycharm it says the hs-test-python dependency isn't satisfied. any attempts to install the package prove futile. rendering running any further tests impossible.
![image](https://user-images.githubusercontent.com/10232964/80508056-3b2f5b80-8980-11ea-8301-e80dbd4ff564.png)

**Comment by aaaaaa2493** [comment]
Hi! Looks like anaconda cannot download packages located on GitHub. You can try to install the library using an absolute path `pip install https://github.com/hyperskill/hs-test-python/archive/v2.0.1.tar.gz`. Make sure that it is installed in the virtual environment that is created for this PyCharm project. 

Another way is to use regular python, it is proved to work in Python 3.7 and 3.8. You can choose an interpreter when downloading the project from the Hyperksill. This way, this library will be installed automatically.

**Comment by lNyx** [comment]
when i tried opening the project with regular python 3.7 interpreter before, it couldn't install the package either. but the manual installation worked, thanks!
